:concurrency: 10
:queues:
  - default
  - mailers
  - critical
  - low
:timeout: 30
:logfile: ./log/sidekiq.log

:redis:
  url: <%= ENV["REDIS_URL"] %>
  sentinels:
    - host: <%= ENV['REDIS_SENTINEL_1_HOST'] || 'sentinel-1' %>
      port: <%= ENV['REDIS_SENTINEL_1_PORT'] || 26379 %>
    - host: <%= ENV['REDIS_SENTINEL_2_HOST'] %>
      port: <%= ENV['REDIS_SENTINEL_2_PORT'] || 26379 %>
    - host: <%= ENV['REDIS_SENTINEL_3_HOST'] || 'sentinel-3' %>
      port: <%= ENV['REDIS_SENTINEL_3_PORT'] || 26379 %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  role: :master
  master_name: mymaster
